import UKButton from "@tcsw/uikit-solid/src/components/button/UKButton.jsx";
import UKStackItem from "@tcsw/uikit-solid/src/components/stack/UKStackItem.jsx";
import {createResource, Suspense, type Component} from "solid-js";
import trpc from "../../../../lib/trpc";
import styles from "./MethodTwoFactor.module.scss"
import UKText from "@tcsw/uikit-solid/src/components/text/UKText.jsx";
import UKIcon from "@tcsw/uikit-solid/src/components/icon/UKIcon.jsx";

const MethodTwoFactor: Component = () => {
    const [ hasTwoFactor, {refetch: refetchHasTwoFactor} ] = createResource(() => trpc.authentication.hasTwoFactor.query());

    return (
        <UKStackItem
            leading={{
                type: "icon",
                value: "shield_lock",
            }}
            labelText="Two Factor Authentication"
            supportingText={hasTwoFactor() ? "You have OTP two-factor authentication enabled" : "Setup OTP two-factor authentication"}
            onCollapse={() => {
                refetchHasTwoFactor();
            }}
            inlineComponent={hasTwoFactor() && <UKIcon class={styles.enabledIcon}>check</UKIcon>}
            expandedComponent={
                <Suspense>
                    <div class={styles.expanded}>
                        <UKText role="body" size="m">
                            Use an OTP passcode to verify it's really you trying to login. {!hasTwoFactor() ? "\nOnce enabled, you must provide the otp code generated by a supported authenticator app to login / perform certain actions. \n(If you lose access to the authenticator app, you must contact an administrator to regain access to your account.)" : ""}
                        </UKText>
                        <UKButton
                            disabled={true}
                            class={styles.button}
                            onClick={async () => {
                                return 0
                            }}
                        >
                            {hasTwoFactor() ? "Reset" : "Setup"} OTP two factor
                        </UKButton>
                    </div>
                </Suspense>
            }
        />
    );
}

export default MethodTwoFactor