import CHECK_ICON from "@material-symbols/svg-700/outlined/check.svg";
import SHIELD_LOCK_ICON from "@material-symbols/svg-700/outlined/shield_lock.svg";
import UKButton from "@onlineworkspace/uikit-solid/src/components/button/UKButton.jsx";
import UKDialog from "@onlineworkspace/uikit-solid/src/components/dialog/UKDialog.jsx";
import UKIcon from "@onlineworkspace/uikit-solid/src/components/icon/UKIcon.jsx";
import UKStackItem from "@onlineworkspace/uikit-solid/src/components/stack/UKStackItem.jsx";
import UKText from "@onlineworkspace/uikit-solid/src/components/text/UKText.jsx";
import { type Component, createResource, createSignal, Suspense } from "solid-js";
import trpc from "../../../../lib/trpc";
import TwoFactorCreateCodeDialog from "./components/TwoFactorCreateCodeDialog/TwoFactorCreateCodeDialog";
import styles from "./MethodTwoFactor.module.scss";

const MethodTwoFactor: Component = () => {
  const [hasTwoFactor, { refetch: refetchHasTwoFactor }] = createResource(() => trpc.authentication.hasTwoFactor.query());
  const [showDialog, setShowDialog] = createSignal<"createCode" | "confirmCode" | null>(null);

  return (
    <>
      <UKStackItem
        leading={{
          type: "icon",
          value: SHIELD_LOCK_ICON,
          alt: "two factor authentication",
        }}
        labelText="Two Factor Authentication"
        supportingText={hasTwoFactor() ? "You have OTP two-factor authentication enabled" : "Setup OTP two-factor authentication"}
        inlineComponent={hasTwoFactor() && <UKIcon class={styles.enabledIcon}>{CHECK_ICON}</UKIcon>}
        expandedComponent={
          <Suspense>
            <div class={styles.expanded}>
              <UKText role="body" size="m">
                Use an OTP passcode to verify it's really you trying to login.{" "}
                {!hasTwoFactor()
                  ? "\nOnce enabled, you must provide the otp code generated by a supported authenticator app to login / perform certain actions. \n(If you lose access to the authenticator app, you must contact an administrator to regain access to your account.)"
                  : ""}
              </UKText>
              <UKButton
                class={styles.button}
                onClick={async () => {
                  setShowDialog("createCode");
                  return;
                }}
              >
                {hasTwoFactor() ? "Reset" : "Setup"} OTP two factor
              </UKButton>
            </div>
          </Suspense>
        }
      />
      <UKDialog onClose={() => setShowDialog(null)} show={() => showDialog() === "createCode"}>
        <TwoFactorCreateCodeDialog />
      </UKDialog>
    </>
  );
};

export default MethodTwoFactor;
